url: "https://rdf-models.github.io/whiskey"
baseurl: "/whiskey"

theme: jekyll-theme-slate

title: Whiskey Ontology
description: A linked data model representation of core concepts regarding whiskey for the IA Conference

show_downloads: true
github:
  zip_url: https://github.com/rdf-models/whiskey/archive/master.zip
  tar_url: https://github.com/rdf-models/whiskey/archive/master.tar.gz
